server:
  port: 4567

es:
  cluster:
    name: qa2elk
    host: 127.0.0.1,172.24.80.90,172.24.80.91
    port: 9300


mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml

spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/test
     username: root
     password: 0109QWe
#     type: com.alibaba.druid.pool.DruidDataSource

#druid:
#  initial-size: 8 #初始化连接大小
#  min-idle: 5 #最小空闲连接数
#  max-active: 10 #最大连接数
#  query-timeout: 6000 #查询超时时间
#  transaction-query-timeout: 6000 #事务查询超时时间
#  remove-abandoned-timeout: 1800 #关闭空闲连接超时时间
#  filter-class-names: stat
#  filters: stat,config