package top.treegrowth.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import top.treegrowth.mybatis.model.My;
import top.treegrowth.mybatis.model.MyExample;

@Mapper
public interface MyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my
     *
     * @mbg.generated
     */
    long countByExample(MyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my
     *
     * @mbg.generated
     */
    int deleteByExample(MyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my
     *
     * @mbg.generated
     */
    int insert(My record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my
     *
     * @mbg.generated
     */
    int insertSelective(My record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my
     *
     * @mbg.generated
     */
    List<My> selectByExample(MyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") My record, @Param("example") MyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") My record, @Param("example") MyExample example);
}