package top.treegrowth.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import top.treegrowth.mybatis.model.You;
import top.treegrowth.mybatis.model.YouExample;

@Mapper
public interface YouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table you
     *
     * @mbg.generated
     */
    long countByExample(YouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table you
     *
     * @mbg.generated
     */
    int deleteByExample(YouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table you
     *
     * @mbg.generated
     */
    int insert(You record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table you
     *
     * @mbg.generated
     */
    int insertSelective(You record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table you
     *
     * @mbg.generated
     */
    List<You> selectByExample(YouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table you
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") You record, @Param("example") YouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table you
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") You record, @Param("example") YouExample example);
}